# Generated by Django 5.1.6 on 2025-03-03 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todochallengeApp', '0002_rename_nombre_tareas_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
